### ISSUE TITLE
login and register functionality 

### ISSUE THREAD

**Issue by AliDurul** [Night-Birdss/FullStack_Blog-App#11]
states are not filling with res from api after login or register

**Comment by nurdoganbahadir** [comment]
Kontrol edicem hocam

**Comment by AliDurul** [comment]
> Hocam kontrol ettim söylediğinizi doğrumu anladım tabi bilmiyorum ama login ve register işlemleri çalışıyor slice içerisindeki username ve token bilgiside doluyor

Hmm, mustafa hocayla bir deneme yapin onda token ici dolmuyordu en son hocam.

**Comment by nurdoganbahadir** [comment]
tamam hocam bir araya geldiğimizde bir bakarım mustafa hocanın kodlarına
